// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDi1XGquO6ppsKy8uxxwKpn5qrf33PMqKk',
    appId: '1:220878119768:web:ce2182f9da347b7996fb2d',
    messagingSenderId: '220878119768',
    projectId: 'task-e-commerce-f2dee',
    authDomain: 'task-e-commerce-f2dee.firebaseapp.com',
    storageBucket: 'task-e-commerce-f2dee.firebasestorage.app',
    measurementId: 'G-DNVDR4W4QC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAc2fUtoNqE5UXhsIhTP54fL8s19wYArYQ',
    appId: '1:220878119768:android:0aa9e71898e5279296fb2d',
    messagingSenderId: '220878119768',
    projectId: 'task-e-commerce-f2dee',
    storageBucket: 'task-e-commerce-f2dee.firebasestorage.app',
  );

}